<%@ Page Title="" Language="C#" MasterPageFile="~/PagePrincipal.Master" AutoEventWireup="true" CodeBehind="GestionClient.aspx.cs" Inherits="Exercice_de_Revision_WCS_1.WebForm1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:GridView ID="GridView1" runat="server" ShowHeaderWhenEmpty="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Compte" DataSourceID="SqlDataSource1">
        <Columns>
            <asp:BoundField DataField="Compte" HeaderText="Compte" ReadOnly="True" SortExpression="Compte" />
            <asp:BoundField DataField="Nom" HeaderText="Nom" SortExpression="Nom" />
            <asp:BoundField DataField="Prenom" HeaderText="Prenom" SortExpression="Prenom" />
            <asp:BoundField DataField="Adresse" HeaderText="Adresse" SortExpression="Adresse" />
            <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:MonConnection %>" 
        SelectCommand="SELECT [Compte], [Nom], [Prenom], [Adresse], [Email] FROM [Client]"
        UpdateCommand="update [Client] set Nom=@Nom,Prenom=@Prenom,Adresse=@Adresse,Email=@Email where Compte=@Compte"
        DeleteCommand="delete from [Client] where Compte=@Compte"
        ></asp:SqlDataSource>
    <table>
        <tr>
            <td>
                <label>Compte</label>
            </td>
            <td>
                <asp:TextBox CssClass="text" ID="Compte" runat="server" />
                <asp:RequiredFieldValidator ControlToValidate="Compte" runat="server" Text="*" ErrorMessage="*" ForeColor="Red" />
            </td>
        </tr>
        
        <tr>
            <td>
                <label>Nom</label>
            </td>
            <td>
                <asp:TextBox CssClass="text" ID="Nom" runat="server" />
                <asp:RequiredFieldValidator ControlToValidate="Nom" runat="server" Text="*" ErrorMessage="*" ForeColor="Red" />
            </td>
        </tr>

        <tr>
            <td>
                <label>Prenom</label>
            </td>
            <td>
                <asp:TextBox CssClass="text" ID="Prenom" runat="server" />
                <asp:RequiredFieldValidator ControlToValidate="Prenom" runat="server" Text="*" ErrorMessage="*" ForeColor="Red" />
            </td>
        </tr>

        <tr>
            <td>
                <label>Adresse</label>
            </td>
            <td>
                <asp:TextBox CssClass="text" ID="Adresse" runat="server" />
                <asp:RequiredFieldValidator ControlToValidate="Adresse" runat="server" Text="*" ErrorMessage="*" ForeColor="Red" />
            </td>
        </tr>

        <tr>
            <td>
                <label>Email</label>
            </td>
            <td>
                <asp:TextBox CssClass="text" ID="Email" runat="server" />
                <asp:RegularExpressionValidator ControlToValidate="Email" Text="*" ForeColor="Red" ErrorMessage="Incorrect email" runat="server" ValidationExpression="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"/>
            </td>
        </tr>
         <tr>
            <td>
                <label>Mot Pass</label>
            </td>
            <td>
                <asp:TextBox CssClass="text" TextMode="Password" ID="MotPass" runat="server" />
                <asp:RegularExpressionValidator ControlToValidate="MotPass" Text="*" ForeColor="Red" ErrorMessage="Mininmum 8 caracteres" runat="server" ValidationExpression="\w{8,}"/>
            </td>
        </tr>
        <tr>
            <td>
                <asp:Button ID="Ajouter" CssClass="btn" Text="Ajouter" runat="server" OnClick="Ajouter_Click" />
            </td>
            <td>
                <asp:Label ID="Message" runat="server" />
            </td>
        </tr>
    </table>
</asp:Content>
